/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_spcgreenville_deagan_physical_SystemManagementBus */

#ifndef _Included_org_spcgreenville_deagan_physical_SystemManagementBus
#define _Included_org_spcgreenville_deagan_physical_SystemManagementBus
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_spcgreenville_deagan_physical_SystemManagementBus
 * Method:    readByteNative
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_spcgreenville_deagan_physical_SystemManagementBus_readByteNative
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     org_spcgreenville_deagan_physical_SystemManagementBus
 * Method:    writeByteNative
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_org_spcgreenville_deagan_physical_SystemManagementBus_writeByteNative
  (JNIEnv *, jobject, jint, jint, jint);

/*
 * Class:     org_spcgreenville_deagan_physical_SystemManagementBus
 * Method:    initializeFileDescriptor
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_spcgreenville_deagan_physical_SystemManagementBus_initializeFileDescriptor
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
