/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_spcgreenville_deagan_physical_GPIOChipInfoProvider */

#ifndef _Included_org_spcgreenville_deagan_physical_GPIOChipInfoProvider
#define _Included_org_spcgreenville_deagan_physical_GPIOChipInfoProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_spcgreenville_deagan_physical_GPIOChipInfoProvider
 * Method:    getGPIOChipInfoInternal
 * Signature: (Ljava/lang/String;)Lorg/spcgreenville/deagan/physical/GPIOChipInfoProvider/GPIOChipInfo;
 */
JNIEXPORT jobject JNICALL Java_org_spcgreenville_deagan_physical_GPIOChipInfoProvider_getGPIOChipInfoInternal
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
