/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_spcgreenville_deagan_physical_EdgeDetector */

#ifndef _Included_org_spcgreenville_deagan_physical_EdgeDetector
#define _Included_org_spcgreenville_deagan_physical_EdgeDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_spcgreenville_deagan_physical_EdgeDetector
 * Method:    beginEdgeDetection
 * Signature: (Lorg/spcgreenville/deagan/physical/EdgeDetectCallback;)I
 */
JNIEXPORT jint JNICALL Java_org_spcgreenville_deagan_physical_EdgeDetector_beginEdgeDetection
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
